server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: search_route
          uri: lb://mail-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://third-party-service
          predicates:
            - Path=/api/third/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://mail-coupon
          predicates:
              - Path=/api/coupon/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: depository_route
          uri: lb://mail-depository
          predicates:
              - Path=/api/depository/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://mail-order
          predicates:
             - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://mail-product
          predicates:
              - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: user_route
          uri: lb://mail-user
          predicates:
              - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}




