server:
  port: 8060

spring:
  redis:
    host: 192.168.152.128
  main:
    allow-bean-definition-overriding: true
  cloud:
    alibaba:
      seata:
        tx-service-group: mail_group

seata:
  tx-service-group: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: c06b9718-71c8-400c-8946-fca15d0968ab
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      data-id: seataServer.properties
  registry:
    type: nacos
    preferred-networks: 30.240.*
    nacos:
      application: mail-seata
      server-addr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      namespace:
      username: nacos
      password: nacos

mail:
  thread:
    core-size: 10
    max-size: 100
    keep-alive-time: 10

logging:
  level:
    com.mail: info
    com.alibaba.nacos.client.naming: warn